name: 'Run checks and build pull requests'

on:
  pull_request:
    paths:
      - '**'

jobs:
  checks-and-build:
    name: Run checks and build
    uses: ./.github/workflows/reusable-checks-and-build.yml

  wait-for-required-jobs:
    name: Wait for jobs required for pull requests to be merge-able
    runs-on: ubuntu-latest
    if: always()
    needs: [checks-and-build]
    steps:
      - name: Checkout the repository so that the Bash script is accessible
        uses: actions/checkout@v5
      - name: Exit 1 if one of the `needs` was a failure
        run: ./.github/scripts/exit-1-if-result-failure-was-passed.sh "${{ toJSON(needs) }}"
